name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: install asdf-vm
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf
      
      - name: install glow and run test
        run: . $HOME/asdf/asdf.sh
          asdf plugin add glow $GITHUB_WORKSPACE
          asdf list all glow
          asdf install glow latest
          glow --version
